#############################################################################
# Makefile for building: 5640_linux_qt
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  5640_linux_qt.pro
# Template: app
# Command: /opt/alinx/zynq_qt5.7.1/bin/qmake -spec arm-linux-gnueabihf-g++ CONFIG+=debug CONFIG+=qml_debug DEFINES+=zynq -o Makefile 5640_linux_qt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -Dzynq -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/alinx/opencv_zynq_lib/include -I-L/home/zgh/ncnn/build-arm-linux-gnueabihf/install/include/ -I/opt/alinx/zynq_qt5.7.1/include -I/opt/alinx/zynq_qt5.7.1/include/QtWidgets -I/opt/alinx/zynq_qt5.7.1/include/QtGui -I/opt/alinx/zynq_qt5.7.1/include/QtCore -I. -I. -I/opt/alinx/zynq_qt5.7.1/mkspecs/arm-linux-gnueabihf-g++
QMAKE         = /opt/alinx/zynq_qt5.7.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 5640_linux_qt1.0.0
DISTDIR = /home/zgh/qtprojectforMTCNN-master/.tmp/5640_linux_qt1.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-rpath,/opt/alinx/zynq_qt5.7.1/lib
LIBS          = $(SUBLIBS) -L/opt/alinx/opencv_zynq_lib/lib -lz -lv4l2 -lv4l1 -lv4lconvert -lavcodec -lavformat -lavutil -lswscale -lswresample -lx264 -lxvidcore -lpng -ljpeg -ltiff -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -ldl -L/home/zgh/ncnn/build-arm-linux-gnueabihf/install/lib -lncnn -L/opt/alinx/zynq_qt5.7.1/lib -lQt5Widgets -lQt5Gui -lQt5Core -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mtcnn.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mtcnn.o \
		moc_mainwindow.o
DIST          = /opt/alinx/zynq_qt5.7.1/mkspecs/features/spec_pre.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/unix.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/linux.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/sanitize.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/gcc-base.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/gcc-base-unix.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/g++-base.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/g++-unix.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/qconfig.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_charts.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_core.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gui.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_network.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_script.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_sql.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_svg.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_xml.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt_functions.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt_config.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/arm-linux-gnueabihf-g++/qmake.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/toolchain.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/default_pre.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/resolve_config.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/default_post.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/qml_debug.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/warn_on.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/resources.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/moc.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/uic.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/unix/thread.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/file_copies.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/testcase_targets.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/exceptions.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/yacc.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/lex.prf \
		5640_linux_qt.pro mainwindow.h main.cpp \
		mainwindow.cpp \
		mtcnn.cpp
QMAKE_TARGET  = 5640_linux_qt
DESTDIR       = 
TARGET        = 5640_linux_qt


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 5640_linux_qt.pro /opt/alinx/zynq_qt5.7.1/mkspecs/arm-linux-gnueabihf-g++/qmake.conf /opt/alinx/zynq_qt5.7.1/mkspecs/features/spec_pre.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/unix.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/linux.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/sanitize.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/gcc-base.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/gcc-base-unix.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/g++-base.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/common/g++-unix.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/qconfig.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_charts.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_core.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gui.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_network.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_script.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_sql.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_svg.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_xml.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt_functions.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt_config.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/arm-linux-gnueabihf-g++/qmake.conf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/toolchain.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/default_pre.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/resolve_config.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/default_post.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/qml_debug.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/warn_on.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/resources.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/moc.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/uic.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/unix/thread.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/file_copies.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/testcase_targets.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/exceptions.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/yacc.prf \
		/opt/alinx/zynq_qt5.7.1/mkspecs/features/lex.prf \
		5640_linux_qt.pro \
		/opt/alinx/zynq_qt5.7.1/lib/libQt5Widgets.prl \
		/opt/alinx/zynq_qt5.7.1/lib/libQt5Gui.prl \
		/opt/alinx/zynq_qt5.7.1/lib/libQt5Core.prl
	$(QMAKE) -spec arm-linux-gnueabihf-g++ CONFIG+=debug CONFIG+=qml_debug DEFINES+=zynq -o Makefile 5640_linux_qt.pro
/opt/alinx/zynq_qt5.7.1/mkspecs/features/spec_pre.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/common/unix.conf:
/opt/alinx/zynq_qt5.7.1/mkspecs/common/linux.conf:
/opt/alinx/zynq_qt5.7.1/mkspecs/common/sanitize.conf:
/opt/alinx/zynq_qt5.7.1/mkspecs/common/gcc-base.conf:
/opt/alinx/zynq_qt5.7.1/mkspecs/common/gcc-base-unix.conf:
/opt/alinx/zynq_qt5.7.1/mkspecs/common/g++-base.conf:
/opt/alinx/zynq_qt5.7.1/mkspecs/common/g++-unix.conf:
/opt/alinx/zynq_qt5.7.1/mkspecs/qconfig.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_charts.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_charts_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_concurrent.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_core.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_core_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gamepad.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gui.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_gui_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_network.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_network_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_printsupport.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_script.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_script_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_scripttools.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_sql.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_sql_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_svg.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_svg_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_testlib.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_widgets.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_xml.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_xml_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt_functions.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt_config.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/arm-linux-gnueabihf-g++/qmake.conf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/exclusive_builds.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/toolchain.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/default_pre.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/resolve_config.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/default_post.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/qml_debug.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/warn_on.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/qt.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/resources.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/moc.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/uic.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/unix/thread.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/file_copies.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/testcase_targets.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/exceptions.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/yacc.prf:
/opt/alinx/zynq_qt5.7.1/mkspecs/features/lex.prf:
5640_linux_qt.pro:
/opt/alinx/zynq_qt5.7.1/lib/libQt5Widgets.prl:
/opt/alinx/zynq_qt5.7.1/lib/libQt5Gui.prl:
/opt/alinx/zynq_qt5.7.1/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec arm-linux-gnueabihf-g++ CONFIG+=debug CONFIG+=qml_debug DEFINES+=zynq -o Makefile 5640_linux_qt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp mtcnn.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /opt/alinx/zynq_qt5.7.1/include/QtWidgets/QMainWindow \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qmainwindow.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qwidget.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qwindowdefs.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qglobal.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qconfig.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfeatures.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsystemdetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qprocessordetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcompilerdetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtypeinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtypetraits.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qisenum.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsysinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlogging.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qflags.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbasicatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_bootstrap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qgenericatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_cxx11.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_msvc.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qglobalstatic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmutex.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qnumeric.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qversiontagging.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobjectdefs.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qnamespace.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobjectdefs_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qwindowdefs_win.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobject.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstring.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qchar.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbytearray.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qrefcount.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qarraydata.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringbuilder.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qalgorithms.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qiterator.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qhashfunctions.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qpair.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbytearraylist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringlist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qregexp.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringmatcher.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcoreevent.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qscopedpointer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmetatype.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvarlengtharray.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcontainerfwd.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobject_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmargins.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpaintdevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qrect.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsize.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qpoint.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpalette.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qcolor.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qrgb.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qrgba64.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qbrush.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvector.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qmatrix.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpolygon.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qregion.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdatastream.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qiodevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qline.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qtransform.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpainterpath.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qimage.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpixelformat.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpixmap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsharedpointer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qshareddata.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qhash.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsharedpointer_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfont.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfontmetrics.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfontinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qsizepolicy.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qcursor.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qkeysequence.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qevent.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvariant.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdebug.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtextstream.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlocale.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qset.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcontiguouscache.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qurl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qurlquery.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfile.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfiledevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qvector2d.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qtouchdevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qtabwidget.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qicon.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QFileDialog \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qfiledialog.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdir.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfileinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qdialog.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/QPixmap \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/QImage \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QLabel \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qlabel.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qframe.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/QTimer \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtimer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbasictimer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/QThread \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qthread.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/opencv.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvdef.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/hal/interface.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/version.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/base.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvstd.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/ptr.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/neon_utils.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/traits.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/matx.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/saturate.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/fast_math.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/types.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/mat.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/bufferpool.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/mat.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/persistence.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/operations.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvstd.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/utility.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/core_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/types_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/optim.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc/imgproc_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc/types_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/photo.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/photo/photo_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/tracking.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/background_segm.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/tracking_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/features2d.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/miniflann.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/defines.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/config.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect/objdetect_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/calib3d.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/affine.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/calib3d/calib3d_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgcodecs.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/videoio.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/highgui.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/highgui/highgui_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/videoio/videoio_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/ml.hpp \
		mtcnn.h \
		net.h \
		platform.h \
		blob.h \
		layer.h \
		mat.h \
		allocator.h \
		gpu.h \
		option.h \
		modelbin.h \
		paramdict.h \
		command.h \
		pipeline.h \
		mainwindow.h \
		/opt/alinx/zynq_qt5.7.1/bin/moc
	/opt/alinx/zynq_qt5.7.1/bin/moc $(DEFINES) -I/opt/alinx/zynq_qt5.7.1/mkspecs/arm-linux-gnueabihf-g++ -I/home/zgh/qtprojectforMTCNN-master -I/opt/alinx/opencv_zynq_lib/include -I/home/zgh/qtprojectforMTCNN-master/-L/home/zgh/ncnn/build-arm-linux-gnueabihf/install/include -I/opt/alinx/zynq_qt5.7.1/include -I/opt/alinx/zynq_qt5.7.1/include/QtWidgets -I/opt/alinx/zynq_qt5.7.1/include/QtGui -I/opt/alinx/zynq_qt5.7.1/include/QtCore -I/opt/Xilinx/SDK/2017.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/include/c++/6.2.1 -I/opt/Xilinx/SDK/2017.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/include/c++/6.2.1/arm-linux-gnueabihf -I/opt/Xilinx/SDK/2017.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/include/c++/6.2.1/backward -I/opt/Xilinx/SDK/2017.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/lib/gcc/arm-linux-gnueabihf/6.2.1/include -I/opt/Xilinx/SDK/2017.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/lib/gcc/arm-linux-gnueabihf/6.2.1/include-fixed -I/opt/Xilinx/SDK/2017.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/include -I/opt/Xilinx/SDK/2017.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/opt/alinx/zynq_qt5.7.1/bin/uic
	/opt/alinx/zynq_qt5.7.1/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QMainWindow \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qmainwindow.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qwidget.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qwindowdefs.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qglobal.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qconfig.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfeatures.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsystemdetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qprocessordetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcompilerdetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtypeinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtypetraits.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qisenum.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsysinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlogging.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qflags.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbasicatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_bootstrap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qgenericatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_cxx11.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_msvc.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qglobalstatic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmutex.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qnumeric.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qversiontagging.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobjectdefs.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qnamespace.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobjectdefs_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qwindowdefs_win.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobject.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstring.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qchar.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbytearray.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qrefcount.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qarraydata.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringbuilder.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qalgorithms.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qiterator.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qhashfunctions.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qpair.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbytearraylist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringlist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qregexp.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringmatcher.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcoreevent.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qscopedpointer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmetatype.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvarlengtharray.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcontainerfwd.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobject_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmargins.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpaintdevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qrect.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsize.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qpoint.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpalette.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qcolor.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qrgb.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qrgba64.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qbrush.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvector.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qmatrix.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpolygon.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qregion.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdatastream.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qiodevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qline.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qtransform.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpainterpath.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qimage.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpixelformat.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpixmap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsharedpointer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qshareddata.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qhash.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsharedpointer_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfont.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfontmetrics.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfontinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qsizepolicy.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qcursor.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qkeysequence.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qevent.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvariant.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdebug.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtextstream.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlocale.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qset.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcontiguouscache.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qurl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qurlquery.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfile.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfiledevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qvector2d.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qtouchdevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qtabwidget.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qicon.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QFileDialog \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qfiledialog.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdir.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfileinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qdialog.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/QPixmap \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/QImage \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QLabel \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qlabel.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qframe.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/QTimer \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtimer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbasictimer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/QThread \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qthread.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/opencv.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvdef.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/hal/interface.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/version.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/base.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvstd.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/ptr.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/neon_utils.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/traits.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/matx.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/saturate.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/fast_math.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/types.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/mat.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/bufferpool.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/mat.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/persistence.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/operations.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvstd.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/utility.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/core_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/types_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/optim.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc/imgproc_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc/types_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/photo.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/photo/photo_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/tracking.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/background_segm.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/tracking_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/features2d.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/miniflann.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/defines.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/config.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect/objdetect_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/calib3d.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/affine.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/calib3d/calib3d_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgcodecs.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/videoio.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/highgui.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/highgui/highgui_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/videoio/videoio_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/ml.hpp \
		mtcnn.h \
		net.h \
		platform.h \
		blob.h \
		layer.h \
		mat.h \
		allocator.h \
		gpu.h \
		option.h \
		modelbin.h \
		paramdict.h \
		command.h \
		pipeline.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QApplication \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qapplication.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcoreapplication.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qeventloop.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qdesktopwidget.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qguiapplication.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QMainWindow \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qmainwindow.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qwidget.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qwindowdefs.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qglobal.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qconfig.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfeatures.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsystemdetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qprocessordetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcompilerdetection.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtypeinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtypetraits.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qisenum.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsysinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlogging.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qflags.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbasicatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_bootstrap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qgenericatomic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_cxx11.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qatomic_msvc.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qglobalstatic.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmutex.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qnumeric.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qversiontagging.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobjectdefs.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qnamespace.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobjectdefs_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qwindowdefs_win.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobject.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstring.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qchar.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbytearray.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qrefcount.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qarraydata.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringbuilder.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qalgorithms.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qiterator.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qhashfunctions.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qpair.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbytearraylist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringlist.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qregexp.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qstringmatcher.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcoreevent.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qscopedpointer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmetatype.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvarlengtharray.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcontainerfwd.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qobject_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmargins.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpaintdevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qrect.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsize.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qpoint.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpalette.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qcolor.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qrgb.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qrgba64.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qbrush.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvector.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qmatrix.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpolygon.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qregion.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdatastream.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qiodevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qline.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qtransform.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpainterpath.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qimage.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpixelformat.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qpixmap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsharedpointer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qshareddata.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qhash.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qsharedpointer_impl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfont.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfontmetrics.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qfontinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qsizepolicy.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qcursor.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qkeysequence.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qevent.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qvariant.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qmap.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdebug.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtextstream.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qlocale.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qset.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcontiguouscache.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qurl.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qurlquery.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfile.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfiledevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qvector2d.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qtouchdevice.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qtabwidget.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qicon.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QFileDialog \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qfiledialog.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qdir.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qfileinfo.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qdialog.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/QPixmap \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/QImage \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QLabel \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qlabel.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qframe.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/QTimer \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qtimer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qbasictimer.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/QThread \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qthread.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/opencv.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvdef.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/hal/interface.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/version.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/base.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvstd.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/ptr.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/neon_utils.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/traits.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/matx.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/saturate.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/fast_math.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/types.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/mat.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/bufferpool.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/mat.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/persistence.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/operations.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/cvstd.inl.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/utility.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/core_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/types_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/optim.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc/imgproc_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgproc/types_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/photo.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/photo/photo_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/tracking.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/background_segm.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/video/tracking_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/features2d.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/miniflann.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/defines.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/flann/config.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/objdetect/objdetect_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/calib3d.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/core/affine.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/calib3d/calib3d_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgcodecs.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/videoio.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/highgui.hpp \
		/opt/alinx/opencv_zynq_lib/include/opencv2/highgui/highgui_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/videoio/videoio_c.h \
		/opt/alinx/opencv_zynq_lib/include/opencv2/ml.hpp \
		mtcnn.h \
		net.h \
		platform.h \
		blob.h \
		layer.h \
		mat.h \
		allocator.h \
		gpu.h \
		option.h \
		modelbin.h \
		paramdict.h \
		command.h \
		pipeline.h \
		ui_mainwindow.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/QVariant \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QAction \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qaction.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qactiongroup.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QApplication \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qapplication.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qcoreapplication.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qeventloop.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qdesktopwidget.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qguiapplication.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qinputmethod.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QButtonGroup \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qbuttongroup.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QHeaderView \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qheaderview.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qabstractitemview.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qabstractscrollarea.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qabstractitemmodel.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qitemselectionmodel.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qabstractitemdelegate.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qstyleoption.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qabstractspinbox.h \
		/opt/alinx/zynq_qt5.7.1/include/QtGui/qvalidator.h \
		/opt/alinx/zynq_qt5.7.1/include/QtCore/qregularexpression.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qslider.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qabstractslider.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qstyle.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qtabbar.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qrubberband.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QMenuBar \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qmenubar.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qmenu.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QPushButton \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qpushbutton.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qabstractbutton.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QStatusBar \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qstatusbar.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QToolBar \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/qtoolbar.h \
		/opt/alinx/zynq_qt5.7.1/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mtcnn.o: mtcnn.cpp mtcnn.h \
		net.h \
		platform.h \
		blob.h \
		layer.h \
		mat.h \
		allocator.h \
		gpu.h \
		option.h \
		modelbin.h \
		paramdict.h \
		command.h \
		pipeline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mtcnn.o mtcnn.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

